name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
        Scala: ['2.12.18', '2.13.12', '3.3.1']
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java }}
    - name: Run tests
      env:
        SCALA_VERSION: ${{ matrix.Scala }}
      run: sbt ";set Test / g8 / g8Properties ~= { _ + (\"scala_version\" -> \"$SCALA_VERSION\")}; g8Test"
